BPS-383/앨범 수정 기능 추가
Bluekey-Payment-System/BPS-FE pull request #132
Opened 2023-11-03 18:13 UTC by SeyoungCho

## 해당 사항 (중복 선택)

- [X] FEAT : 새로운 기능 추가 및 개선
- [X] FIX : 버그 수정
- [ ] REFACTOR : 결과의 변경 없이 코드의 구조를 재조정
- [ ] STYLE : 코드 스타일에 관련된 변경 사항
- [ ] DOCS : 코드가 아닌 문서를 수정한 경우
- [ ] REMOVE : 파일을 삭제하는 작업만 수행
- [ ] RENAME : 파일 또는 폴더명을 수정하거나 위치(경로)를 변경
- [ ] CHORE : 패키지 매니저 설정, 코드 수정 없이 설정 변경(eslint) 등 기타 사항

## 설명

### Key Changes

- 앨범 수정 기능을 추가했습니다.

### How it Works

- 앨범 이름, 커버이미지, 대표 아티스트에 대한 수정 요청 api를 연동했습니다.
- 수정이 정상적으로 완료되면 해당 앨범 정보를 사용하는 캐시를 무효화 합니다.
### To Reviewers

2023-11-03 18:16 UTC, SeyoungCho commented on src/components/album/AddTrackModal/AddTrackForm.tsx
> +                                setValue(`artists.${index}.commissionRate`, value.commissionRate || 0);
오리지널 트랙이 체크되어있는 경우는 요율에 영향이 없도록 하였습니다.

2023-11-03 18:16 UTC, SeyoungCho commented on src/components/album/AlbumForm/AlbumForm.tsx
> +              return item.id === watch("memberId");
드롭다운의 디폴트값을 앨범 정보에서 가져옵니다

2023-11-03 18:17 UTC, SeyoungCho commented on src/services/queries/albums/useUpdateAlbumInfo.ts
> +        void queryClient.invalidateQueries({ queryKey: [DASHBOARD_TYPE.ALBUM, "dashboard", "albumInfo", data.albumId] });
앨범 id에 대한 쿼리키가 number타입임을 인지하고 바꾸었습니다.

2023-11-05 07:13 UTC, drizzle96 requested changes
테스트 해보니 쿼리 아티스트 변경한 후 쿼리 무효화가 안되고 있는 것처럼 보여서,, 한 번 확인 부탁드립니다ㅠㅠ
쿼리키에 ["albums", "NaN"] 이라는 친구가 들어가는데 이게 원인일 수도 있을 것 같아요

![DemoCreatorRec_2023-11-05-16-08-18](https://github.com/Bluekey-Payment-System/BPS-FE/assets/125791542/cda63fa4-a58b-4fc3-a5a0-444eaaef6849)

2023-11-06 09:35 UTC, drizzle96 commented on src/services/queries/albums/useAlbumInfo.ts
> +    ["albums", albumId],
아하 쿼리키값에 리터럴로 넣은게 원인이었군요...! ⭐

2023-11-06 09:36 UTC, drizzle96 approved these changes
잘 작동하는거 확인했습니다! 수고하셨습니다 😀

2023-11-08 01:33 UTC, merged