BPS-88/MonthlyTrendsChart 컴포넌트 제작
Bluekey-Payment-System/BPS-FE pull request #39
Opened 2023-08-17 10:09 UTC by wookki

## 해당 사항 (중복 선택)

- [x] FEAT : 새로운 기능 추가 및 개선
- [ ] FIX : 버그 수정
- [ ] REFACTOR : 결과의 변경 없이 코드의 구조를 재조정
- [ ] STYLE : 코드 스타일에 관련된 변경 사항
- [ ] DOCS : 코드가 아닌 문서를 수정한 경우
- [ ] REMOVE : 파일을 삭제하는 작업만 수행
- [ ] RENAME : 파일 또는 폴더명을 수정하거나 위치(경로)를 변경
- [ ] CHORE : 패키지 매니저 설정, 코드 수정 없이 설정 변경(eslint) 등 기타 사항

## 설명

### Key Changes
- 월별 매출/정산액 차트 컴포넌트제작
- type이 "SUPER_ADMIN" 이거나 "ADMIN"인 경우 회사 이익, 매출액이 보이며 "ARTIST"인 경우 정산액, 매출액이 보여집니다

### How it Works

### To Reviewers

2023-08-17 11:29 UTC, drizzle96 requested changes
PR 내용과 브랜치명이 일치하지 않는 것 같아요
88에서 하위 이슈를 파야할 것 같습니다!

2023-08-17 11:29 UTC, drizzle96 commented on src/components/dashboard/MonthlyTrendsChart.tsx
> +  barChartData: ChartDataProps[],
지금은 상관없는데 MOCK 데이터 연동시킬 때는 MOCK 타입에 맞게 손을 봐야할지도 몰겠네용

2023-08-17 11:29 UTC, drizzle96 commented on src/components/dashboard/MonthlyTrendsChart.tsx
common처럼 도메인(dashboard) 안에 컴포넌트 폴더 만들고 그 안에 tsx를 위치시키는게 맞는 것 같아요~!

2023-08-17 11:33 UTC, drizzle96 approved these changes

2023-08-18 08:35 UTC, SeyoungCho commented on src/components/common/Chart/BarChart/BarChart.tsx
> +  const keyType = type === "ARTIST" ? ["settlement", "revenue"] : ["netIncome", "revenue"];
이거 ARTIST로 쓰면 별로 안좋아요. MEMBER_TYPE을 export한다음에 MEMBER_TYPE.ARTIST로 쓰는게 좋을것 같습니다

2023-08-18 17:20 UTC, hayoung-99 approved these changes
수고하셨습니다 👍👍

2023-08-18 17:20 UTC, hayoung-99 commented on src/components/common/Chart/BarChart/BarChart.tsx
> +  const keyType = type === "ARTIST" ? ["settlement", "revenue"] : ["netIncome", "revenue"];
음 여기 말고도 dto 작업 이전에 했던 것들 중에 리터럴로 한게 있을 것 같은데 언제 한번 싹 정리해야겠네요!

2023-08-18 17:20 UTC, hayoung-99 commented on src/components/common/Chart/BarChart/BarChart.utils.ts
> +    if (type === "ARTIST") {
여기도 수정부탁드립니다!

2023-08-18 17:20 UTC, hayoung-99 commented on src/components/dashboard/MonthlyTrendsChart.module.scss
> +      display: flex;
```suggestion
      @include flexbox(row);
```

2023-08-18 17:20 UTC, hayoung-99 commented on src/components/dashboard/MonthlyTrendsChart.tsx
> +        <span>{`월별 ${type === "ARTIST" ? "정산액" : "매출"} 추이`}</span>
여기도 수정부탁드립니다!

2023-08-19 07:13 UTC, wookki commented on src/components/dashboard/MonthlyTrendsChart.tsx
수정완료!

2023-08-19 07:17 UTC, wookki commented on src/components/common/Chart/BarChart/BarChart.tsx
> +  const keyType = type === "ARTIST" ? ["settlement", "revenue"] : ["netIncome", "revenue"];
수정완료! export가 안돼서 그냥 literal로 때려박았네요 수정했슴다~!

2023-08-19 07:18 UTC, wookki commented on src/components/common/Chart/BarChart/BarChart.utils.ts
> +    if (type === "ARTIST") {
수정완료

2023-08-19 07:26 UTC, wookki commented on src/components/common/Chart/BarChart/BarChart.utils.ts
> +    if (type === "ARTIST") {
수정완료!

2023-08-19 08:04 UTC, wookki commented on src/components/dashboard/MonthlyTrendsChart.tsx
> +        <span>{`월별 ${type === "ARTIST" ? "정산액" : "매출"} 추이`}</span>
수정완료!

2023-08-19 08:05 UTC, wookki commented on src/components/dashboard/MonthlyTrendsChart.module.scss
> +      display: flex;
수정완료

2023-08-19 08:18 UTC, merged