BPS-96/어드민 회원가입 페이지 추가
Bluekey-Payment-System/BPS-FE pull request #42
Opened 2023-08-18 08:34 UTC by SeyoungCho

## 해당 사항 (중복 선택)

- [X] FEAT : 새로운 기능 추가 및 개선
- [ ] FIX : 버그 수정
- [ ] REFACTOR : 결과의 변경 없이 코드의 구조를 재조정
- [ ] STYLE : 코드 스타일에 관련된 변경 사항
- [X] DOCS : 코드가 아닌 문서를 수정한 경우
- [ ] REMOVE : 파일을 삭제하는 작업만 수행
- [ ] RENAME : 파일 또는 폴더명을 수정하거나 위치(경로)를 변경
- [ ] CHORE : 패키지 매니저 설정, 코드 수정 없이 설정 변경(eslint) 등 기타 사항

## 설명

### Key Changes

- 어드민 회원가입 페이지를 추가했습니다. 경로는 `/admin/signup`입니다. 
- 회원가입 페이지에서 렌더링할 `SignupForm`컴포넌트를 추가했습니다. 
### How it Works

- 회원가입 폼을 하나 렌더링 하는 페이지입니다. SignupForm 컴포넌트 내부에서 useForm훅을 사용하여 각 인풋 필드에 register를 합니다.
- 각 인풋 필드마다 validation로직이 독립적으로 돕니다. 모든 필드는 required필드입니다. 
![image](https://github.com/Bluekey-Payment-System/BPS-FE/assets/45449387/533665ed-2fe2-426b-b024-709b6e060271)
![image](https://github.com/Bluekey-Payment-System/BPS-FE/assets/45449387/7219a406-33e3-459e-b08d-a534c3761746)

### To Reviewers

- 아이디 중복 검사는 form을 submit하기 전에도 가능은 하지만 중복 검사를 해서 true, false만 반환하는 api가 추가되어야 해서 그냥 submit할때 오는 에러 메세지로 판단하는것이 좋겠습니다.

2023-08-18 12:14 UTC, drizzle96 requested changes
폼 활용되는거 보니까 신기하군요...!!! 고생하셨습니다~~ ⭐

근데 로고랑 ver 1.0.0이 뷰포트 상하단에 고정돼있다보니까 1300px 이하에서 레이아웃이 깨지는 것 같은데 확인 필요할 것 같습니다 😂

2023-08-18 12:14 UTC, drizzle96 commented on src/components/auth/SignupForm.tsx/SignupForm.tsx
폴더명 수정해주세요!

2023-08-18 12:15 UTC, drizzle96 approved these changes

2023-08-18 13:26 UTC, SeyoungCho commented on src/components/auth/SignupForm.tsx/SignupForm.tsx
헐 실수있었네요 감사합니다

2023-08-18 17:23 UTC, hayoung-99 approved these changes
좋은 유틸 함수들 감사합니다. 잘 사용할게요 👍
그건 그렇고 리액트 훅 폼 소년가장이시네요

2023-08-18 17:23 UTC, hayoung-99 commented on src/components/auth/SigninForm/SigninForm.tsx
> +  type: AdminType | ArtistType;
👍

2023-08-18 17:23 UTC, hayoung-99 commented on src/types/enums/user.enum.ts
> +export const MEMBER_TYPE = {
export로 바꿔주셨군용 감사합니다!

2023-08-19 05:49 UTC, wookki approved these changes
고생 많으셨어요!!

2023-08-19 05:49 UTC, wookki commented on src/components/auth/SigninForm/SigninForm.tsx
> +      <Spacing size={98} />
Spacing 너무 좋아요!

2023-08-19 05:49 UTC, wookki commented on src/types/enums/user.enum.ts
> +export const MEMBER_TYPE = {
저도 이거 고쳤어요 ㅋㅋ 감사함다!

2023-08-19 05:49 UTC, wookki commented on src/components/auth/SigninForm/SigninForm.tsx
> +      {type === MEMBER_TYPE.ADMIN && (
디자인 시안에는 아티스트 로그인 페이지에 회원가입이 있는데 아티스트는 회원가입을 어드민 거쳐서 해야하니 시안이 잘못된 것 같네요  

<img width="266" alt="스크린샷 2023-08-19 오후 2 39 08" src="https://github.com/Bluekey-Payment-System/BPS-FE/assets/103362820/729f1ff0-ef5f-4e46-99e5-55574234918c">

2023-08-19 05:49 UTC, wookki commented on src/components/auth/SigninForm/SigninForm.tsx
> +            {" "}
사이 간격을 margin을 주지 않고 {" "} 하는 것도 방법이군요!!

2023-08-19 05:49 UTC, wookki commented on src/components/auth/SignupForm/SignupForm.tsx
> +      <Spacing size={16} />
사이 간격이 30인데 이거 너무 굿입니다
<img width="243" alt="스크린샷 2023-08-19 오후 2 43 59" src="https://github.com/Bluekey-Payment-System/BPS-FE/assets/103362820/6c34923d-aa50-4995-88f0-34bd762d4680">

2023-08-19 05:49 UTC, wookki commented on src/utils/getYearFromUrl.ts
> + * getYearFromUrl 유틸 함수
함수 잘 사용하겠습니다! 감사합니다

2023-08-19 08:04 UTC, merged