BPS-48/input 기능이 추가된 드롭다운 제작
Bluekey-Payment-System/BPS-FE pull request #5
Opened 2023-08-07 12:02 UTC by wookki

## 해당 사항 (중복 선택)

- [x] FEAT : 새로운 기능 추가 및 개선
- [ ] FIX : 버그 수정
- [ ] REFACTOR : 결과의 변경 없이 코드의 구조를 재조정
- [ ] STYLE : 코드 스타일에 관련된 변경 사항
- [ ] DOCS : 코드가 아닌 문서를 수정한 경우
- [ ] REMOVE : 파일을 삭제하는 작업만 수행
- [ ] RENAME : 파일 또는 폴더명을 수정하거나 위치(경로)를 변경
- [ ] CHORE : 패키지 매니저 설정, 코드 수정 없이 설정 변경(eslint) 등 기타 사항

## 설명

### Key Changes
![image](https://github.com/Bluekey-Payment-System/BPS-FE/assets/103362820/048aa01f-0c2a-4c01-98da-e486b62dcc7e)

- input 기능이 추가된 드롭다운을 제작하였습니다.

### How it Works

- 간단한 로직 설명
<img width="625" alt="스크린샷 2023-08-07 오후 8 56 22" src="https://github.com/Bluekey-Payment-System/BPS-FE/assets/103362820/1bd656f0-c392-4602-9b55-7a840b00567d">

 - 이전에 만들었던 드롭다운과 마찬가지로 `dropdownListData={["혁기", "아이유", "볼빨간사춘기", "할아버지"]} 리스트 데이터를 넣어줍니다. 여기서 input이 있는 기능을 사용하고 싶으면 `withInput={true}`값만 넣어주시면 돼요!

### To Reviewers

- 스타일링은 미완성인 상태입니다. 리아님에게 이 컴포넌트가 어디서 사용될지 말씀드린 상태라 추후에 리아님이 제작해주시는대로 디자인을 반영해서 재수정하겠습니다!

2023-08-07 12:29 UTC, wookki commented on src/components/common/Dropdown/DropdownWithInput/DropdownListWithInput.tsx
> +  const [inputValue, setInputValue] = useState("");
initial에 초기값을 이용해서 타입을 지정하면 자동으로 `const [inputValue, setInputValue] = useState<string>("")과 동일한 효과가 나타나지않나유??

2023-08-08 02:25 UTC, drizzle96 approved these changes
수고하셨습니다~~!

2023-08-08 02:25 UTC, drizzle96 commented on src/components/common/Dropdown/DropdownSelectedValue.tsx
>          className={cx("userInput", theme === "black" && "blackTheme")}
className={cx("userInput", {[theme]: theme})} 으로 변경해도 되겠네요!

2023-08-08 02:25 UTC, drizzle96 commented on src/components/common/Dropdown/DropdownSelectedValue.tsx
>          id="toggle"
class와 따로 id를 설정한 이유가 뭔지 궁금해요

2023-08-08 02:25 UTC, drizzle96 commented on src/components/common/Dropdown/DropdownSelectedValue.tsx
>          id="toggle"
그리고 26번 줄 cx로 통일하면 좋을 것 같아요

2023-08-08 02:25 UTC, drizzle96 commented on src/components/common/Dropdown/Dropdown.tsx
> +      withInput={withInput}
컨벤션에 따르면 hasInput / includesInput 이 더 맞다고 생각합니다..!

> convention
> 
> - 명사로 작성한다.
> - 예외) boolean 변수는 is~ has~ includes~ 등의 현재형 동사로 시작한다.

2023-08-08 02:25 UTC, drizzle96 commented on src/components/common/Dropdown/DropdownWithInput/DropdownListWithInput.tsx
> +  const filteredDropDownList = dropdownListData.filter((dropdownItem) => { return dropdownItem.includes(inputValue); });
꼭 고칠 필요는 없지만 아래처럼 변경하면 오류를 해결할 수 있기는 해요!

```
  const filteredDropDownList = dropdownListData.filter((dropdownItem) => {
    return dropdownItem.includes(inputValue);
  });
```

2023-08-08 02:25 UTC, drizzle96 commented on src/components/common/Dropdown/DropdownWithInput/DropdownListWithInput.tsx
> +  const filteredDropDownList = dropdownListData.filter((dropdownItem) => { return dropdownItem.includes(inputValue); });
curly brack start 후, end 전에 포맷하는 룰을 왜 추가 안했냐라고 한다면,
이것저것 옵션 건드려봤는데 모든 케이스를 다 커버하지 못하고 자꾸 튀는(=맘에 안드는) 케이스가 생기더라구요
그래서 그냥 룰을 안넣었어요

2023-08-08 02:30 UTC, drizzle96 commented on src/components/common/Dropdown/Dropdown.tsx
> +const Dropdown = ({ dropdownListData, theme = "white", withInput = false }: DropdownProps) => {
theme 내용 바꿔주신다고 한 부분 기록 용도!

2023-08-08 02:37 UTC, hayoung-99 requested changes

2023-08-08 02:37 UTC, hayoung-99 commented on src/components/common/Dropdown/Dropdown.tsx
> +  withInput?: boolean
검색기능 추가하는 prop으로 이해하고 있는데, 변수 의미가 더 명확하면 좋을 것 같아요
ex) `withSearch`

2023-08-08 02:47 UTC, wookki commented on src/components/common/Dropdown/Dropdown.tsx
> +  withInput?: boolean
좋아요!

2023-08-08 02:47 UTC, wookki commented on src/components/common/Dropdown/Dropdown.tsx
> +const Dropdown = ({ dropdownListData, theme = "white", withInput = false }: DropdownProps) => {
캄사!

2023-08-08 02:48 UTC, wookki commented on src/components/common/Dropdown/DropdownWithInput/DropdownListWithInput.tsx
> +  const filteredDropDownList = dropdownListData.filter((dropdownItem) => { return dropdownItem.includes(inputValue); });
알겠습니다!

2023-08-08 03:14 UTC, wookki commented on src/components/common/Dropdown/Dropdown.tsx
> +  withInput?: boolean
수정완료

2023-08-08 03:15 UTC, wookki commented on src/components/common/Dropdown/Dropdown.tsx
> +const Dropdown = ({ dropdownListData, theme = "white", withInput = false }: DropdownProps) => {
수정완료

2023-08-08 03:34 UTC, merged